kobotoolbox/kobocat

fabfile.py
Understand `~` character in key file paths; fall back on current directory if `DEPLOYMENTS_JSON` unset
=> Minor fabfile changes

onadata/apps/main/tests/test_form_permissions.py, onadata/apps/main/views.py
Fix `onadata.apps.main.views.set_perm()` so that it becomes possible to remove the `report_xform` permission.
=> Include 'report_xform' when removing permissions

onadata/apps/viewer/static/js/stats_tables.js
The data returned by the API (e.g. /api/v1/stats/submissions/8850?group=intro/Interviewer_s_name) looks like `[{"count": 1, "intro/Interviewer_s_name": "Lawrence "}]`, reflecting that `Interviewer_s_name` is within the group `intro`. The identifiers with slashes are [created by `XFormInstanceParser`](https://github.com/kobotoolbox/kobocat/blob/eeeeb870acffe6f74902d0b5a5319d55b683ef17/onadata/apps/logger/xform_instance_parser.py#L287).
Likewise, the client [parses form.json and sets and `xpath` attribute for each question](https://github.com/kobotoolbox/kobocat/blob/eeeeb870acffe6f74902d0b5a5319d55b683ef17/onadata/apps/viewer/static/js/xform.js#L184). However, the "Analyze data" table-creation code tell Backgrid.js that it should [simply use the `name` …
=> Fixes TP 1704

onadata/libs/utils/image_tools.py
Fixes at least one issue with /api/v1/media.
=> If an initial attempt to save a thumbnail fails, convert to RGB and retry

onadata/apps/api/viewsets/briefcase_api.py, onadata/apps/api/viewsets/xform_list_api.py, onadata/apps/api/viewsets/xform_submission_api.py, onadata/libs/authentication.py, onadata/settings/common.py
Now allows basic authentication over HTTPS by default. Unencrypted basic authentication is prohibited for everything except XForm submission.
=> Make API authentication more consistent

fabfile.py
Rename `celeryd` to `kc_celeryd`. Other projects using Celery will each have their own Upstart jobs for now.
=> Change fabfile to match renamed Celery Upstart job

onadata/settings/kc_environ.py
DJANGO_ALLOWED_HOSTS environment variable is a space-separated list
which is pulled into settings.
https://docs.djangoproject.com/en/1.8/ref/settings/#allowed-hosts
=> adding ALLOWED_HOSTS to kc_environ

onadata/apps/api/tools.py, onadata/apps/api/viewsets/xform_viewset.py, onadata/libs/filters.py, onadata/libs/serializers/xform_serializer.py
Allow filtering forms by `id_string`; allow `PATCH`ing to update form contents via `text_xls_form` or `xls_file` in the request
Closes #138 
Supersedes #154
=> Forms API redeployment enhancements

onadata/apps/survey_report/templates/survey_report/auto_report.html, onadata/apps/survey_report/templates/survey_report/export_menu.html
This simply moves the header elements in the right location of the template (outside of the `block content`) for auto reports and advanced exports.
=> Header fix

onadata/libs/serializers/xform_serializer.py
Copied verbatim from XFormListSerializer. Unsure why one doesn't inherit from
the other, but no time to investigate that now
=> Include `hash` field in XFormSerializer; closes #209

docker/run_celery.bash, onadata/apps/logger/management/commands/fix_root_node_names.py, onadata/apps/logger/tasks.py, onadata/settings/kc_environ.py
Fixes #242 
**Deployment requirements**
1. Run `./manage.py fix_root_node_names` once, manually and note the last instance ID;
1. Set `ISSUE_242_MINIMUM_INSTANCE_ID` equal to that instance ID in the environment;
1. Make sure Celery can see that environment variable;
1. Modify the Celery worker invocation to include `--beat` ([example](https://github.com/kobotoolbox/kobocat/compare/242-issue?expand=1#diff-7bfe1ebf2993514abe091c3d6bff396cR10)), otherwise the scheduled task won't run.
=> Logic to fix mismatched root node names

Dockerfile
Necessary for [this](https://github.com/kobotoolbox/kobo-docker/pull/55/files#diff-7bf48f97567fbe49782099935360b5e6L26).
=> Remove outdated reference to directory `wsgi`.

requirements/base.pip
Only references to Memcached are:
https://github.com/kobotoolbox/kobocat/blob/master/onadata/settings/production_example.py#L68
https://github.com/kobotoolbox/kobocat/blob/master/script/install/macos#L9-L10
https://github.com/kobotoolbox/kobocat/blob/master/script/install/ubuntu#L22-L23
=> Remove unused `pylibmc` (Memcached).

onadata/apps/viewer/tasks.py, onadata/settings/common.py
...which can be overridden by environment variables:
* CELERYD_MAX_CONCURRENCY: lesser of 6 or number of CPU cores
* CELERYD_MAX_TASKS_PER_CHILD: 7
* CELERYD_TASK_TIME_LIMIT: 2100 seconds (35 minutes)
* CELERYD_TASK_SOFT_TIME_LIMIT: 1800 seconds (30 minutes)
=> Configure useful Celery limits; fixes #250

onadata/koboform/pyxform_utils.py
...in "sheeted CSV" form representations, e.g. `""` in
settings
,form_title,version,id_string
,Sample Title,1234,sample_title
choices
""
survey
[snip]
["Sheeted CSV" reference](https://github.com/kobotoolbox/kpi/blob/cd9ac187fa1fc6fc44c72c66ae56b265fa5944f7/jsapp/xlform/src/csv.coffee#L240)
[Flowdock discussion](https://www.flowdock.com/app/kobotoolbox/kobo/threads/RLV8oVNY9oi_8vDMoBZCvZ3-v_O)
[Support request](https://kobotoolbox.desk.com/agent/case/3190)
=> Tolerate empty, nameless worksheets

onadata/koboform/pyxform_utils.py
Fixes `invalid worksheet name u''` when using 'View data in table' or 'Analyze data'
=> Remove blank lines in CSV before converting to XLS

onadata/apps/logger/management/commands/fix_root_node_names.py, onadata/apps/logger/tasks.py
* Option for a minimum starting form ID
* Explicitly order query sets by ID
* Wrap XML processing in `try...except` and print errors without aborting the entire task
=> Improve management command for #242

fabfile.py
Also removes unused `sudo` import
=> Always pass `pty=False` to Fabric's `run()`

onadata/apps/api/tests/viewsets/test_data_viewset.py, onadata/apps/api/viewsets/data_viewset.py
=> Fixed `/api/v1/data/{pk}/{dataid}`, was different to docs and list view

onadata/apps/main/views.py
Fixes third checkbox item: After making any changes in the kc iframe settings screen, the page refreshes and shows the KC project dashboard instead of the settings box. It now loads the referring page instead.
=> Partial fix for KPI #716

requirements/base.pip
Fixes `'module' object has no attribute 'backend'`
Dimagi merged [my PR](https://github.com/dimagi/django-digest/pull/16) long ago, so there's no need to keep using my repository. Unfortunately, PyPI is still very out-of-date, having been last updated 2011-03-04.
=> Use Dimagi's django-digest for proper 1.8 support

Dockerfile
[`MEDIA_ROOT`](https://github.com/kobotoolbox/kobocat/blob/master/onadata/settings/kc_environ.py#L70) location changed since [change to `PROJECT_ROOT` in `4b2b30`](https://github.com/kobotoolbox/kobocat/commit/4b2b30bd4c93c967bd219c66fb81a6816f24d9f6#diff-fe503402bfe64d2b53a020632d2aacb7R28).
Inspired by kobotoolbox/kobo-docker#68.
=> Preserve correct media directory in Docker.

onadata/apps/api/permissions.py, onadata/apps/api/viewsets/data_viewset.py
* Return 404 if submission specified by `dataid` does not belong to form
identified by `pk`
* Return 404 (anonymous) or 401 (authenticated) in the list and detail views if
form identified by `pk` does not have `shared_data = True`
=> Correct API data endpoint behavior

fabfile/docker.py, fabfile/legacy.py
Also removes obsolete `key_filename` logic
=> Use `docker-compose build` when fab deploying

docker/run_celery.bash
Should avoid worker subprocesses sitting idle despite many queued jobs. Other
change: remove time limit and tasks per child settings from the command line
since b6e30094 provides for them to be specified in environment variables
=> Invoke the Celery worker with `-Ofair`; fixes #329

requirements/base.pip
If your database is large, the migration included in this update of
django-reversion will be slow. For example, on a database with 3.3 million rows
in the `reversion_version` table, the migration takes about 20 minutes. This
can be reduced to around 7 minutes on the same size of database by checking out
commit e822bb1 (from https://github.com/etianen/django-reversion/pull/611).
=> Upgrade reversion to 2.0.8. Read WARNING below!

onadata/apps/logger/tasks.py, onadata/apps/logger/views.py, onadata/apps/main/urls.py, requirements/base.pip, requirements/s3.pip
Quick-and-dirty; fixes #340. URL remains `https://server/username/superuser_stats`, but now that view kicks off a Celery task and returns the destination filename immediately, while the contents of the report are generated in the background.
=> Generate `superuser_stats` ZIP asynchronously

onadata/apps/viewer/models/data_dictionary.py
Update the pyxform.survey.Survey object to reflect
the intended name (rather than the name pulled from
the filename)
Mimics code in formpack that explicitly sets root
node name:
https://github.com/kobotoolbox/formpack/commit/048c53fe96c7681ac806cbc90615353c7b988782#diff-f6ef579a49ba75d5146b5a04da43002dR93
closes #358
=> reflect intended name rather than filename

onadata/apps/logger/management/commands/fix_root_node_names.py, onadata/apps/logger/tasks.py, onadata/settings/kc_environ.py
* Set `ISSUE_242_INSTANCE_XML_SEARCH_STRING` to an empty string in the
environment to consider all `Instance`s. Otherwise, it defaults to
`uploaded_form_` for backwards compatibility
* Completes in 5 minutes on a database with 3 mil. `Instance`s and
10,000+ corrections needed
=> Rewrite `fix_root_node_names`; fixes #361

onadata/apps/viewer/tasks.py, onadata/settings/kc_environ.py
Fixes #315. Failures will be sent to Sentry (if Raven is enabled).
=> Log warnings for stuck exports; mark them "failed"

requirements/base.pip
See kobotoolbox/tasks#137
Deploying this now to https://kc.du.kbtdev.org/ for testing
=> Require Pyxform with namespaces support

onadata/settings/kc_environ.py
Please deliver us from uWSGI deadlocks. Fixes #377
=> Set `disable_existing_loggers` to `True`

onadata/apps/logger/migrations/0003_add-index-on-attachment-media-file.py, onadata/apps/logger/migrations/0004_increase-length-of-attachment-mimetype-field.py, onadata/apps/logger/models/attachment.py, onadata/apps/viewer/views.py
According to this bug: https://github.com/kobotoolbox/tasks/issues/153, I've added an index on `media_file` field in table `Attachment` and increased `mime_type` field up to 100 characters.
In the Python code, there was a possibilty that `result` could be reached without being initialized.
I've indented the code below first `if` to avoid `result` variable to be undefined whenever `if`returns `false`.
When `result` is set, it's a list of `Assignment` objects, so instead of calling `result.count()` - which is a call to database -, I've changed the calculation with `len` method for python lists.
=> Slow count queries

docker/cron/clean_up_tmp, docker/init.bash
According to https://github.com/kobotoolbox/kobo-docker/issues/149 issue found in kobo-docker repository. 
As already discussed, I've also commented auto-created migrations command in init.bash
=> Periodically clean up KC temporary files & remove auto-created migrations.

onadata/apps/main/models/user_profile.py, onadata/settings/kc_environ.py
...which appears in the UI as "Require authentication to see forms and
submit data". This affects *NEW USERS* only! To change existing users, use the
Django shell and follow the example below:
```
kobocat$ ./manage.py shell
(InteractiveConsole)
>>> from onadata.apps.main.models import UserProfile
>>> updated_count = UserProfile.objects.update(require_auth=True)
>>> updated_count
6
```
Closes #335
=> Configurable default for `UserProfile.require_auth`

onadata/apps/logger/models/instance.py
Fixes #401. Thanks to @jeverling for reporting the problem.
=> Remove `encode()` to fix non-ASCII XML hashing

onadata/apps/logger/models/attachment.py, onadata/libs/utils/logger_tools.py
across multiple POST requests. Adhere to the OpenRosa specification.
Don't lose data. Fixes #432; fixes kobotoolbox/kpi#1679. Fixes, hopefully,
kobotoolbox/enketo-express#776.
=> Save all attachments when a submission is split

onadata/libs/utils/viewer_tools.py, onadata/settings/common.py
I've added another validation in case INTERNAL_DOMAIN_NAME is equal to PUBLIC_DOMAIN_NAME.
In that case, we don't want to force the protocol.
Fixes #445
=> "Could not connect with Server" when editing after configuring new internal URLs - fix

onadata/apps/logger/fixtures/repeated_group/repeated_group.json, onadata/apps/logger/fixtures/repeated_group/repeated_group.xml, onadata/apps/logger/tests/test_parsing.py, onadata/apps/logger/xform_instance_parser.py, onadata/settings/test_environ.py
As discussed with @jnm, multiple nodes with the same name are now allowed (even if they don't belong to a repeated group)
Fixes #426
=> Deleting a repeat breaks parsing of existing submissions - fix

fabfile/docker.py
when deploying with Fabric. Fixes kobotoolbox/tasks#261
=> Do not manually stop or remove containers

Dockerfile, Dockerfile.kobocat_base, onadata/settings/common.py, requirements/s3.pip
and increase the lifespan of ZIP exports to 24 hours. Fixes #456.
Builds on top of #455.
=> Fix memory leak by requiring a newer version of django-storages

Dockerfile, Dockerfile.kobocat_base, requirements/s3.pip
* Fix typo in `boto` requirement;
* Upgrade `pip` from 8 to better-behaved 10;
* Check `s3.pip` as well as `base.pip` when building from the main `Dockerfile`.
=> Install S3 requirements properly; fixes #454

onadata/apps/main/tests/test_form_exports.py, onadata/apps/main/urls.py, onadata/apps/viewer/views.py
While checking over https://github.com/kobotoolbox/kobocat/pull/476, I noticed
that https://[kc-host]/[username]/forms/[id_string]/data.zip did not work even
prior to the changes in that PR.
=> Remove (broken) synchronous ZIP export

onadata/libs/utils/export_tools.py, onadata/libs/utils/viewer_tools.py, requirements/s3.pip
exports. Closes #475. See https://github.com/jnm/django-storages/commit/119d8fe694341f2c93afb9c0c3d078ed928ac017 for the meaningful changes.
=> Use a fork of `django-storages` to fix corrupt ZIP

onadata/apps/viewer/views.py
Exports can still be generated with the "New Export" button. Closes #484
=> Disable automatic export creation in `export_list`

onadata/apps/logger/models/instance.py, onadata/libs/utils/logger_tools.py
Try not to do any locking until as close as possible to the end of the
transaction. Closes #490.
We should be able to delete https://github.com/kobotoolbox/kobocat/tree/defer-submission-count after this is merged.
=> Do not lock any rows until attachments are saved 

onadata/apps/logger/migrations/0010_attachment_media_file_basename.py, onadata/apps/logger/models/attachment.py, onadata/apps/viewer/views.py
performance when a single `auth_user` has may rows in `logger_attachment`. This
commit lacks a management command to populate the `media_file_basename` column,
but we'll say that it closes #495.
=> Add a new `media_file_basename` column to improve

onadata/apps/logger/management/commands/populate_media_file_basename.py, onadata/apps/logger/models/attachment.py, onadata/apps/viewer/views.py
Tested with local filesystem and S3.
A command manager has been added to fix other records.
Fixes #500.
=> 500 images collected not found - fix

onadata/apps/logger/migrations/0011_add-index-to-instance-uuid_and_xform_uuid.py
...to merge https://github.com/kobotoolbox/kobocat/pull/395
@noliveleger, this is simple enough, but encountering this conflict makes me wonder if the dropping/adding done by https://github.com/kobotoolbox/kobocat/pull/395 will cause downtime on large databases.
=> Fix migration conflict caused by waiting too long

onadata/apps/api/permissions.py, onadata/apps/api/viewsets/data_viewset.py
by allowing those with the `change_xform` permission to delete submissions.
Fixes #509
=> Make the data API match the `delete_data` view

onadata/apps/logger/templates/downloadSubmission.xml
I originally posted an issue about this in the kobo-kpi repo by mistake, sorry! https://github.com/kobotoolbox/kpi/issues/1863
It turns out that the `media_file` query string value of the `downloadUrl` element of the XML files Kobo generates for Briefcase was being filtered with `safe`, which would be OK for variables interpolated in HTML strings, but for stuff that goes into URLs, we should have a `urlencode` filter instead.
Full disclosure: I haven't tested this. The change is based on Django literature
=> Replace safe filter with urlencode filter in Briefcase API template

onadata/apps/main/urls.py, onadata/apps/main/views.py
Fixes #536.
A new endpoint has been created to be used by UI (i.e. `kpi`) to know what is the correct value.
Maybe frontend could use this endpoint to build media urls instead of an hardcoded value. (cc @magicznyleszek )
=> Bring back old urls for attachments for retro-compability with 'kpi'

onadata/apps/logger/views.py, onadata/apps/main/views.py, onadata/libs/utils/viewer_tools.py, onadata/settings/test_environ.py
Django reads NginX `$http_host` variable to build absolute urls.
When using `runserver_plus`, `$http_host` contains internal port which is incorrect. 
We pass the correct value through the header `X_FORWARD_HTTP_HOST`. 
`Request.META.get('HTTP_HOST')` doesn't report the value correctly where as `request.get_host()` does. 
Fixes #535
=> Used 'request.get_host()' instead of 'request.META.get('HTTP_HOST')'

onadata/libs/utils/image_tools.py
=> Use original file extension when creating thumbnails

onadata/apps/logger/models/attachment.py
=> Quick fix for non-ASCII attachment filenames

onadata/apps/viewer/views.py
Fixes kobotoolbox/kobo-docker#234
Requires https://github.com/kobotoolbox/kobo-docker/pull/238
=> Double-encode S3 URL for `X-Accel-Redirect`

onadata/apps/main/templates/form_photos.html, onadata/apps/main/views.py
and limit the gallery to 2,500 images. Fixes #555
=> Load thumbnails in small, delayed chunks

onadata/apps/logger/management/commands/clean_duplicated_submissions.py, onadata/apps/logger/models/instance.py, onadata/apps/logger/models/xform.py, onadata/libs/utils/logger_tools.py
Fixes #565 
Per our discussion with @jnm (https://www.flowdock.com/app/kobotoolbox/kobo/threads/akW6DmSWpqi8poHX7cOZbahE5oU) 
- A new management command `clean_duplicated_submissions` to delete duplicated submissions (@noliveleger)
- (Pending) Bug fix to avoid other duplicated submissions (@jnm).
=> Duplicated submissions fix

onadata/apps/logger/models/attachment.py, onadata/apps/main/urls.py, onadata/apps/main/views.py, onadata/apps/viewer/management/commands/rewrite_attachments_urls_in_mongo.py, onadata/apps/viewer/models/parsed_instance.py, onadata/libs/utils/image_tools.py, onadata/settings/common.py
- Methods to create thumbnails have been refactoring into one 
- `small`, `medium`, `large` urls have been added to dict saved in Mongo
- Management command to update instances in Mongo
- `media_endpoint` is removed. (Useless because urls are correctly exposed in Mongo now)
=> Update attachments dict for Instance in Mongo

kobocat-template/templates/show.html, onadata/apps/logger/fields.py, onadata/apps/logger/migrations/0012_add_asset_uid_to_xform.py, onadata/apps/logger/models/xform.py, onadata/apps/main/templates/show.html, onadata/apps/main/templates/show_form_settings.html, onadata/apps/restservice/services/kpi_hook.py, onadata/apps/restservice/signals.py
This PR closes #577 but also fixes a bug introduced by https://github.com/kobotoolbox/kobocat/commit/7460cc7b3acd179e0ad0a82ae519ea9bb2ad97b4 where `kpi_hook` endpoint must use `v2`.
=> Use KPI `Asset.uid` when available to build `kpi_hook` endpoint

onadata/apps/logger/models/attachment.py, onadata/apps/viewer/management/commands/rewrite_attachments_urls_in_mongo.py
Closes #588 
**Management command `rewrite_attachments_urls_in_mongo` must be (re)run** to fix existing submissions.
Duplicate of #586 but on top of `2155_kpi_two_databases`.
=> Removed duplicate 'media_file=' argument when building media urls

onadata/apps/main/templates/settings.html, onadata/settings/common.py
Also removes the "change password" button since using that will result in KC and KPI having two different password hashes for the same user. Closes #2595.
=> Invalidate sessions when changing password

onadata/apps/api/permissions.py, onadata/apps/api/viewsets/user_viewset.py
Closes #616. This essentially backports e62a4c9a and 6c250dd2.
NB: the current permissions system makes detail views for
`/api/v1/users` and `/api/v1/profiles` useless to anyone except
superusers; they should probably be removed. See #117.
=> Prevent listing all users and public forms

onadata/settings/common.py
Possibly doesn't do anything because KPI always creates the sessions,
but changed just to cover all bases. Towards kobotoolbox/tasks#336
=> Reduce session timeout to 1 week

onadata/apps/viewer/management/commands/remongo.py, onadata/apps/viewer/management/commands/rewrite_attachments_urls_in_mongo.py, onadata/libs/utils/logger_tools.py
which is not available in all environments. Closes #627. Closes kobotoolbox/kobo-docker#293.
=> Remove calls to MongoDB `fsync`

Dockerfile, docker/dev_wrong_port_warning.py, docker/run_uwsgi.bash, docker/run_uwsgi_wrong_port_warning.bash, docker/wrong_port_warning.wsgi
…instead of 8000. Part of kobotoolbox/kobo-docker#301. Includes warning
for anyone that attempts to connect on 8000, the old port.
https://github.com/kobotoolbox/kobo-docker/pull/302 should be merged after this (and after completing the other steps listed in its description).
=> Listen on port 8001 with uWSGI and `EXPOSE` that

onadata/apps/viewer/models/parsed_instance.py
Same reasoning as https://github.com/kobotoolbox/kpi/pull/2780 (but for `kobocat/master`):
> Removes old check for ObjectId that is not needed anymore:
> 
> Ziggy is dead, so f2his2.
> 
> From this flowdock thread.
> https://www.flowdock.com/app/kobotoolbox/kobo/threads/JWNKW7LKXfzfCpNZpgb9i6lFPWq
=> Removed old check for ziggy

onadata/apps/api/viewsets/xform_viewset.py, onadata/apps/logger/views.py, onadata/libs/utils/viewer_tools.py, onadata/settings/common.py
What's happening (before):
- KPI asks for Enketo Express edit link, it uses KC as a proxy on the private domain name. (e.g. kc.domainname.internal).
- KC POSTs to EE API to get edit link. Among the parameters, KC sends the current domain name
- EE prepares the form in edit mode and create absolute links to media files with the domain it just received.
- All media files are now http://kc.domainname.internal/path.media.file.jpg.
- SSRF blocks them
What happens now:
- KC POSTs to EE API to get edit link. Among the parameters, KC sends the ~~current domain name~~ current public url, e.g, `kc.domainname.org` rather than `*.internal`
- [...]
- SSRF does not block the public url
Some potential caveats:
> @noliveleger Actually, enforce external domain name have some drawbacks too. The request …
=> Make internal KC calls from editing submissions always use public url

onadata/libs/utils/logger_tools.py
…instead of crashing with an unhandled exception. This only affects bulk MongoDB resynchronization, since only `mongo_sync_status()` calls `update_mongo_for_xform()`.
Prevent a system administration command, `./manage.py sync_mongo --remongo`, from failing if it encounters an empty submission
=> Proceed if empty instance found when syncing Mongo

onadata/libs/utils/logger_tools.py
Force OpenRosaResponse message content to be string. In some cases it's prefixed with 'b' caused by the bytestring nature of HttpResponse serialization method.
=> [Python3 and Django2.2 upgrade] Force text messages in OpenRosaResponse

onadata/libs/serializers/xform_serializer.py
1. [N/A] If you've added code that should be tested, add tests
2. [N/A] If you've changed APIs, update (or create!) the documentation
3. [x] Ensure the tests pass
4. [x] Make sure that your code lints and that you've followed our coding style
5. [x] Write a description of your work suitable for publishing on our forum
6. [x] Mention any related issues in this repository (as #ISSUE) and in other repositories (as kobotoolbox/other#ISSUE)
The `<version>` tag in the `formList` will now show the version information based on what was sent to KoBoCat from KPI at the time the form was created or updated. What is returned will depend on when the form was last updated. The possible items that can be returned include the UID, the version number and date, or it may return nothing.
To update this …
=> Updated the formList to return version data

onadata/apps/logger/migrations/0017_remove_xform_sms.py
…and rely instead on the `unique_together` constraint being
automatically removed when its constituent column is dropped
Tested successfully on:
* kc.beta.kbtdev.org
* locally in a new, empty environment
=> Skip AlterUniqueTogether for logger_xform

onadata/libs/serializers/xform_serializer.py, requirements/dev.pip
1. [N/A] If you've added code that should be tested, add tests
2. [N/A] If you've changed APIs, update (or create!) the documentation
3. [x] Ensure the tests pass
4. [x] Make sure that your code lints and that you've followed our coding style
5. [x] Write a description of your work suitable for publishing on our forum
6. [x] Mention any related issues in this repository (as #ISSUE) and in other repositories (as kobotoolbox/other#ISSUE)
The `<version>` tag in the `formList` will now show the version information based on what was sent to KoBoCat from KPI at the time the form was created or updated. What is returned will depend on when the form was last updated. The possible items that can be returned include the UID, the version number and date, or it may return nothing.
To update this …
=> Add version information to form list

kobocat-template/templates/base.html, kobocat-template/templates/legacy_banner.html, kobocat-template/templates/outdated_data_view.html, kobocat-template/templates/outdated_link_guidance.html, kobocat-template/templates/show.html, onadata/apps/main/urls.py, onadata/apps/main/views.py
This will hopefully help ease the transition away from removed features of KoBoCAT's legacy UI, especially for those arriving via anonymous-access links.
Copying to the clipboard with JavaScript does not work in a non-"secure context", e.g. one without HTTPS. Chrome's `chrome://flags/#unsafely-treat-insecure-origin-as-secure` can help you test locally, but I haven't found anything equivalent in Firefox.
=> Add guidance and redirect links to KPI for legacy form and data views

dependencies/pip/dev.in, dependencies/pip/dev.txt, dependencies/pip/prod.txt, dependencies/pip/requirements.in, dependencies/pip/requirements.txt, onadata/apps/api/tests/viewsets/test_metadata_viewset.py, onadata/libs/serializers/metadata_serializer.py
Content type is auto-detected when uploading metadata objects (e.g. media files). (It's not possible to submit it anymore)
It also add a better support for content type detection when attaching remote URLs.
It also fixes an issue that returned a 500 error when trying to modify an existing object
Closes #736 
Closes  #737
=> Improve metadata content type validation

onadata/apps/api/permissions.py, onadata/apps/api/tests/viewsets/test_data_viewset.py, onadata/apps/api/urls.py, onadata/apps/api/viewsets/data_viewset.py, onadata/libs/utils/viewer_tools.py
Implementing the [community requested](https://community.kobotoolbox.org/t/ability-to-view-completed-submissions-in-enketo-and-ideally-pdf-them/15457) feature for view-only submissions (excluding the PDF option for the moment).
The current `kpi` endpoint only returns a URL for editing purposes, accessed with a `GET` request to:
```
https://{kpi_url}/api/v2/assets/{asset_uid}/data/{submission_id}/edit/?return_url=false
```
A view-only URL can now be returned when accessing the new `kpi` endpoint:
```
https://{kpi_url}/api/v2/assets/{asset_uid}/data/{submission_id}/enketo/view/
```
And the edit URL can now be returned when accessing the updated endpoint at:
```
https://{kpi_url}/api/v2/assets/{asset_uid}/data/{submission_id}/enketo/edit/?return_url=false
```
The changes will integrate with …
=> Integrate view-only submissions endpoint from Enketo

onadata/apps/api/models/one_time_auth_token.py
A bug has been introduced with the row level write access feature. 
Users with write access could not edit/validate/delete data anymore while users with partial permissions could.
This PR fixes this issue.
Fixes #753
=> Do not validate referrer by default with one time authentication token

onadata/libs/utils/logger_tools.py, onadata/libs/utils/viewer_tools.py
(by _not_ crashing when `FileSystemStorage` does not allow overwriting the
`seek` method on an export file)
Fixes an issue caused by a2dbb91ce6742e0d33b0a2538f7a8b28d855a0fb
See discussion at
https://community.kobotoolbox.org/t/unable-to-download-zipped-media-files/21142/9?u=jnm
=> Fix local ZIP exports

Dockerfile
The current base image of KPI `nikolaik/python-nodejs:python3.8-nodejs10` does not seem to support other plaforms than `x86_64/amd64`. Using Official Python image makes it possible. 
Morever, KoBoCAT does not need nodejs to be installed.
For example, when we try to build the current image on ARM, docker raises this warning:
```
The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```
=> Add support to multi architecture docker image

Dockerfile, README.md
Taking a first stab at decreasing the docker image size. The benefits of that would be increasing speed for docker pulls (especially for those with slower connections). This would decrease the time it takes to scale up since things like k8s need to pull images on new nodes.
```
kobocat                                    dev.kobofe1639530239   14d155c6188d   10 minutes ago   1.86GB
kobotoolbox/kobocat                        2.021.47               0c477049279b   3 days ago       2.38GB
```
- Use vim.tiny instead of vim (2206 kB vs 36.9 MB)
- Use python:3.8 to install python packages on built stage. Then copy virtual environment into python:3.8-slim. This removes a lot of -dev packages that aren't needed at runtime. It does not break instructions for installing dev dependencies. That did …
=> Reduce docker image size with multi stage build

onadata/apps/api/tests/viewsets/test_xform_submission_api.py, onadata/apps/api/tests/viewsets/test_xform_viewset.py, onadata/apps/api/viewsets/xform_submission_api.py, onadata/apps/api/viewsets/xform_viewset.py, onadata/apps/logger/tests/test_form_submission.py, onadata/apps/logger/views.py, onadata/libs/tests/mixins/make_submission_mixin.py, onadata/libs/tests/utils/test_csv_import.py, onadata/libs/utils/csv_import.py, onadata/libs/utils/logger_tools.py
Forbid anonymous edits to ensure that only owners and those explicitly assigned edit permissions are allowed to edit submissions.
CSV submission imports using the `csv_import` endpoint **may no longer** set `_submitted_by`. This field will now always be overwritten with the username of the user performing the CSV endpoint.
=> Fix edit permission evaluation

dependencies/pip/dev.txt, dependencies/pip/prod.txt, dependencies/pip/requirements.txt
I don't think anything should change about the way we use the client, but I haven't tested it.
See also: https://github.com/transifex/transifex-client/commit/e679ee546e4ceb80150b523748167f9df446bb2d
=> Update transifex-client for Python 3.9

onadata/apps/logger/__init__.py, onadata/apps/logger/signals.py, onadata/apps/logger/xform_instance_parser.py, onadata/libs/utils/logger_tools.py, onadata/settings/base.py, onadata/settings/dev.py
If a submission is deleted, the related attachments (if any) are deleted as well.
=> Delete attachments from storage on submissions deletion

onadata/apps/api/tests/viewsets/test_data_viewset.py, onadata/apps/api/viewsets/data_viewset.py, onadata/apps/api/viewsets/xform_submission_api.py, onadata/apps/logger/tests/test_form_submission.py
It leads to an infinite authentication loop in Enketo. This change rejects such doomed Enketo editing requests with an explanatory message.
Future Enketo editing will be done through KPI; see kobotoolbox/kpi#3654.
More detail, courtesy of @noliveleger:
> You are right, EE does not seem to send DigestAuth headers on POST (even if you are logged in Enketo Express) if  the previous HEAD call does not return a `401` (which is the case when [`required_authentication` is unchecked](https://github.com/kobotoolbox/kobocat/blob/b9c6615cbed6c67748eb6608c2a321209b483369/onadata/apps/api/viewsets/xform_submission_api.py#L179-L180)).
> Therefore the back end always sees the user as `AnonymousUser` when the data is [`POST`ed](https://github.com/kobotoolbox/kobocat/blob/b9c6615cbed6c67748eb6608c2a321209b …
=> Block Enketo editing when anonymous submissions allowed

onadata/settings/base.py
I noticed nginx was returning 403 Forbidden errors on large video uploads. As mentioned in [this](https://stackoverflow.com/a/68186360/15040167) post, it turned out that large files are set by Django to `600` permissions whereas smaller files are `644`.  
I added the `FILE_UPLOAD_PERMISSIONS = 0o644` setting to Django settings, which fixed the problem. 
This prevents a 403 error from occurring when accessing large files attached to submissions on self-hosted instances of KoboToolbox that use local disk storage.
=> Set `FILE_UPLOAD_PERMISSIONS` to prevent 403 when NGINX accesses large submission attachments

docker/init.bash, docker/run_uwsgi.bash
Install Python dependencies before trying to run any Python scripts, fixing errors like `ModuleNotFoundError: No module named 'django_digest'` that previously required a full rebuild to resolve. Mirrors kobotoolbox/kpi#3607.
=> Run `pip-sync` before `manage.py`

.gitlab-ci.yml
- Build docker images on commit, tag as both short sha hash and ref (branch/tag). Push to gitlab docker registry.
- On `beta` branch (and this branch to test) push to a beta instance via helm chart
kobotoolbox/kpi#3600
=> Build Docker images with GitLab CI and deploy to beta instance

onadata/settings/base.py
Same as https://github.com/kobotoolbox/kpi/pull/3708
Kobocat isn't used as much for frontend but some legacy views do make direct requests. So might as well.
=> Enable optional hsts headers via env vars

Dockerfile
This fixes a mistake I made on the on-build changes to reduce the docker image file size. Copying src only into the on build image results in an empty docker image. This is now fixed. I suspect we missed this before because we didn't merge both the docker build/kube PR and the on-build PR. But it's quite obvious now :)
I also removed a stray `rm` that wasn't doing anything. It was running on the build image only, which isn't saved anywhere. So it didn't serve any purpose.
=> Dockerfile: move copying src to runtime image, instead of build step

onadata/settings/base.py
Everything piece of KoboToolbox app is in UTC. 
As per our discussion:
> Let the front end convert UTC to local times
=> Use `UTC` timezone in Django settings

onadata/apps/main/models/meta_data.py
The `update()` itself is atomic, but it remains to be seen if the paired data synchronization logic will suffer without holding these locks for the duration of the entire kobocat request.
@noliveleger, this is already part of 2.022.08b, but I would like a proper review and possible update of the comments I wrote in the code. I don't really understand for how long a `MetaData` row needs to be locked to avoid the KPI-deletion race condition you describe in the comment explaining the original `select_for_update()`. We had a limited internal discussion about this at https://chat.kobotoolbox.org/#narrow/stream/4-Kobo-Dev/topic/paired.20data.20database.20locks/near/97138.
Fix a performance bottleneck in the "Connect Projects" / "dynamic data attachments" feature
=> Remove `select_for_update()` locking from paired data timestamp update

onadata/settings/base.py
This makes it possible to host multiple instances of kobo in the same domain.
=> Allow configurable session cookie name

Dockerfile
Build failing due to https://github.com/jazzband/pip-tools/issues/1617, therefore pin to previous working version.
=> Pin pip version

.github/workflows/pytest.yml, onadata/settings/base.py
Add the possibility to use a secure connection between KPI and MongoDB.
Environment variable `MONGO_USE_TLS` must be passed to the container and should be set to `True`. 
Usually, when a secure connection is enable with `pymongo` the CA certificate should be fetch from server. 
From PyMongo documentation: 
> In many cases connecting to MongoDB over TLS/SSL requires nothing more than passing tls=True as a keyword argument to [MongoClient](https://pymongo.readthedocs.io/en/stable/api/pymongo/mongo_client.html#pymongo.mongo_client.MongoClient)
Unfortunately, some services require to download certificates apart (e.g. AWS DocumentDB). `MONGO_TLS_CA_FILE` can be used to specify the path of certificate
Closes #818 
Related to kobotoolbox/kpi#3807
=> Add support for MongoDB connections over TLS/SSL

.github/workflows/pytest.yml, dependencies/pip/dev.txt, dependencies/pip/prod.txt, dependencies/pip/requirements.in, dependencies/pip/requirements.txt, onadata/apps/api/viewsets/xform_list_api.py, onadata/apps/logger/models/instance.py, onadata/apps/viewer/tasks.py, onadata/libs/mixins/openrosa_headers_mixin.py, onadata/libs/utils/logger_tools.py
1. [x] If you've added code that should be tested, add tests
2. [ ] If you've changed APIs, update (or create!) the documentation
3. [x] Ensure the tests pass
4. [x] Make sure that your code lints and that you've followed [our coding style](https://github.com/kobotoolbox/kpi/blob/master/CONTRIBUTING.md)
5. [x] Write a description of your work suitable for publishing on [our forum](https://community.kobotoolbox.org/tag/release-notes)
6. [x] Mention any related issues in this repository (as #ISSUE) and in other repositories (as kobotoolbox/other#ISSUE)
7. [ ] Open an issue in the [docs](https://github.com/kobotoolbox/docs/issues/new) if there are UI/UX changes
Bring back Python 3.8 support for users who do not use kobo-docker/docker containers.
Starting from Python 3.9, `pytz` has been …
=> Fix `ImportError` with Python 3.8

onadata/settings/base.py
Allow editing Sentry traces rate with env var SENTRY_TRACES_SAMPLE_RATE which defaults to 0.05 (%)
I'm also refactoring it just slightly and preferring the env var SENTRY_DSN with backwards compatibility for RAVEN_DSN. Raven no longer exists. It should match kpi more closely now.
Related to https://github.com/kobotoolbox/kpi/pull/3810
=> Sentry - configure traces rate

onadata/settings/base.py
Implement a new environment variable `MONGO_DB_URL` which gives more flexibility to pass extra parameters (e.g. `tls=True`).
Refer to [MongoDB documentation](https://www.mongodb.com/docs/manual/reference/connection-string/) for connection string format expected in `MONGO_DB_URL` 
These environment variables are deprecated and will be removed in a future release:
- `KOBOCAT_MONGO_HOST`
- `KOBOCAT_MONGO_PORT` 
- `KOBOCAT_MONGO_NAME`
- `KOBOCAT_MONGO_USER`
- `KOBOCAT_MONGO_PASS`
Supersedes #819
Related to kobotoolbox/kpi#3817
=> Allow to pass extra parameters to MongoDB driver

onadata/apps/api/tests/viewsets/test_abstract_viewset.py, onadata/apps/api/tests/viewsets/test_xform_list_api.py, onadata/apps/api/tests/viewsets/test_xform_submission_api.py, onadata/apps/api/viewsets/xform_list_api.py, onadata/apps/viewer/tests/test_export_builder.py
Hopefully fixes the `Parse Error: Expected HTTP/` seen in Enketo when NGINX is not used, e.g. in local development environments. See also kobotoolbox/kpi#3828
=> Make HEAD requests to OpenRosa endpoints return empty responses

onadata/apps/logger/tasks.py
Default 30-minute limit was too short for large instances
=> Raise superuser_stats time limit to one hour

.github/workflows/pytest.yml, .gitlab-ci.yml, dependencies/pip/dev.txt, dependencies/pip/prod.txt, dependencies/pip/requirements.in, dependencies/pip/requirements.txt, onadata/apps/django_digest_backends/cache.py, onadata/apps/django_digest_backends/tests.py, onadata/settings/base.py
This change solves a deadlock issue from the django-digest database nonce storage backend. django-digest can potentially delete a lot of old nonces all at once, while storing a new one. If this happens while an update occurs, which happens when checking an existing nonce, it deadlocks.
This redis based backend fixes this by storing nonces in redis with a TTL. No additional nonce cleanup is necessary. It requires a blocking redis lock to prevent replay attacks. The lock has sane timeouts applied. Because nonces are small and transient, in memory storage is appropriate. Nonces can also be deleted at any time without apparent consequence (I'm still verifying this claim). It would be fine to store these in a ephemeral redis instance if desired.
Introduces new default cache backend that …
=> django-digest redis cache nonce storage backend

onadata/settings/base.py
The recent upgrade of OAuth2 package enforces the requirement of `PKCE` by default.
This requirement is reverted for retro-compatibility.
=> Fix "Code challenge required" error when using OAuth2 applications

Dockerfile
Remove `chmod` command on the virtualenv directory. Additionally, change the `pip` and `pip-tools` install process to match kpi's `Dockerfile`.
Thanks to @noliveleger for debugging!
=> Fix `RemoteNotFoundError` from `pip` at container startup

.github/workflows/pytest.yml, dependencies/pip/dev_requirements.txt, dependencies/pip/requirements.txt
Use `pip-sync` (like in KPI) instead of `pip` directly and bump uWSGI version to 2.0.21
kobotoolbox/kpi#4265
=> Match KPI GitHub Actions pytest workflow

kobocat-template/templates/export_list.html
Allows legacy exports within a KPI to continue working when CSP is enabled
=> Open legacy export download links in a new tab

onadata/apps/viewer/models/data_dictionary.py
Allow `model` to be used as a field name in a form.
closes #486
=> Allow `model` to be used as a field name

.gitlab-ci.yml
Gitlab has [deprecated](https://docs.gitlab.com/ee/update/deprecations.html#ci_build_-predefined-variables) `$CI_BUILD_TOKEN` in favor of `$CI_JOB_TOKEN`, which broke the `build` step of the GitLab actions. This PR updates that constant.
See https://github.com/kobotoolbox/kpi/pull/4433 for a prior PR that fixed this for kpi.
=> Replace deprecated constants in GitLab CI

docker/run_celery.bash
=> Autoscale Celery between 2 and 6 workers and allow configuration via environment variables

.gitlab-ci.yml, Dockerfile
python:3.10 base image now includes openjdk-17-jre; version 11 is removed
=> Upgrade OpenJDK for Debian 12

.github/workflows/pytest.yml, Dockerfile
Fixes broken GitHub CI Python unit tests because of conflicting version of `pip` and `pip-tools`. 
Error is 
> ImportError: cannot import name 'DEV_PKGS' from 'pip._internal.commands.freeze'
CI installs `pip` 23.2 which is not supported by the version of `pip-tools` (6.x.x) frozen in YAML file.
Does not seem to affect `Dockerfile` in release/master branches because Python 3:10 docker image still comes with an older version of `pip` (i.e: 23.0.1)
kobotoolbox/kpi#4547
=> Bump pip-tools version to 7.x.x

onadata/apps/logger/management/commands/populate_submission_counters.py
Fixes crash seen when attempting to migrate kc.unu:
```
Traceback (most recent call last):
File "/srv/src/kobocat/./manage.py", line 17, in <module>
execute_from_command_line(sys.argv)
File "/opt/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
utility.execute()
File "/opt/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 413, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/opt/venv/lib/python3.10/site-packages/django/core/management/base.py", line 354, in run_from_argv
self.execute(*args, **cmd_options)
File "/opt/venv/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
output = self.handle(*args, **options)
File …
```
=> Purge non-dict UserProfile.metadata when calculating submission counters

onadata/apps/logger/migrations/0028_populate_daily_xform_counters_for_year.py
Applying `logger.0028` before `main.0012` (from #885) raises an error (`column main_userprofile.validated_password does not exist`). This PR updates the dependency list for `logger.0028` accordingly.
=> Update populate_xform_submission migration dependencies

README.md, REMOVALS.md, onadata/apps/api/permissions.py, onadata/apps/api/tests/viewsets/test_abstract_viewset.py, onadata/apps/api/tests/viewsets/test_xform_viewset.py, onadata/apps/logger/tests/test_form_submission.py, onadata/apps/main/tests/test_base.py
Users cannot upload, update or delete projects with API `v1` anymore.
KPI Kobocat proxy is still able to use it though. Unit tests have been updated accordingly. 
Scripts / links which still point to this endpoint `/api/v1/forms/` should now use `https://[kpi]/api/v2/assets/` instead.
=> Remove public access to project API endpoint 

onadata/apps/main/migrations/0011_drop_old_kpi_tables.py
Refactors `main.0011_drop_old_kpi_tables` to not print a heavy migration warning every time Django loads the migration file (e.g. when running `./manage.py migrate` for an unrelated app).
=> Prevent SKIP_HEAVY_MIGRATIONS warning unless running the relevant migrations

onadata/apps/logger/management/commands/populate_submission_counters.py, onadata/apps/logger/migrations/0028_add_user_to_daily_submission_counters.py, onadata/apps/logger/migrations/0029_add_user_to_daily_submission_counters.py, onadata/apps/logger/migrations/0029_populate_daily_xform_counters_for_year.py, onadata/apps/logger/models/daily_xform_submission_counter.py, onadata/apps/logger/models/instance.py, onadata/apps/logger/models/xform.py, onadata/apps/logger/tests/models/test_xform_submission_counters.py
DailyXFormSubmissionCounter doesn't actually have a `pre_delete` signal, so the xform=NULL counter isn't getting updated when xforms are deleted. This made sense when it got deleted after 31 days, but now it's our primary way of figuring out submission data on the usage page.
This PR resolves that by making the `DailyXFormSubmissionCounter` function more like the `MonthlyXFormSubmissionCounter`:
* Adding a `user` field
* Adding unique constraints between `user`, `date`, and `xform` (or just the first two when xform=NULL)
* Adding a `pre_delete` signal to update the null counter
A separate PR for kpi will handle updating the shadow model (`ReadOnlyDailyXFormSubmissionCounter`).
I tried to update any place where daily counters are created to include the user. Because this includes the …
=> Create null xform instances for DailyXFormSubmissionCounter

onadata/apps/logger/management/commands/update_attachment_storage_bytes.py, onadata/apps/logger/tasks.py
Return a more accurate global storage metric when user has no projects
Add three new options to management command: 
- `force` to recalculate counters for every user - even those already calculated
- `sync` to recalculate all the counters of users whose profile does not correspond with the projects
- `skip-lock-release` to avoid release submission locks (useful (and faster) when all locks are already released)
=> Improve `update_attachment_storage_bytes` management command

onadata/apps/logger/management/commands/move_media_to_s3.py, onadata/apps/logger/signals.py, onadata/libs/utils/logger_tools.py
Avoid discrepancy when something goes wrong (e.g. one counter is decreased but not the other)
Use `default_storage_class` to get rid of the file on storage instead of letting the FileField `media_file` handle it. 
As explained in the comments of this PR, `attachment.media_file.delete()` could rise to a race condition on counter update.
=> Regroup storage counter calculation in the same DB transaction

onadata/libs/utils/viewer_tools.py
=> Fix failing ZIP exports

onadata/apps/api/tests/viewsets/test_data_viewset.py, onadata/apps/api/viewsets/xform_viewset.py
⚠️  `/api/v1/data/<pk>.<format>` is **deprecated** and `/api/v2/` should be used instead.
For xls(x) and csv formats, please read [this article](https://support.kobotoolbox.org/synchronous_exports.html) and also the [thread in community forum](https://community.kobotoolbox.org/t/how-to-download-data-between-two-dates-from-date-to-date/25569/4) mentioned at the end of the article to use`/api/v2`.
=> Fix 500 error when fetching data with a date range

onadata/apps/logger/management/commands/soft_delete_orphan_attachments.py, onadata/apps/logger/models/instance.py, onadata/apps/logger/models/xform.py, onadata/apps/logger/xform_instance_parser.py
Only process edited submissions
Each submission has two dates, `date_created` and `date_modified`. After some testing, it appeared that `date_modified` is the (almost) same (within a few milliseconds)  than `date_created` when the submission is not edited. 
Assuming that its almost impossible to edit a submission within 10 seconds of the creation, the management command now skips submissions where its modification date is more or less 10 seconds of the creation.
=> Improve `soft_delete_orphan_attachments` management command speed

onadata/apps/logger/management/commands/soft_delete_orphan_attachments_2_023_37c_fix.py, onadata/libs/utils/logger_tools.py
Run `python3 manage.py soft_delete_orphan_attachments_2_023_37c_fix` inside the KoboCAT container to fix existing submissions.
The management command does nothing if no background audio recording and audit logs are soft-deleted. 
This can happen if self-hosters update their instance from an older than version than `2.023.37c` to this one. 
Internal discussion: https://chat.kobotoolbox.org/#narrow/stream/4-Kobo-Dev/topic/Attachments.20incorrectly.20soft.20deleted
=> Fix missing background audio recordings and audit logs when exporting or viewing submitted data

onadata/apps/logger/management/commands/soft_delete_orphan_attachments_2_023_37c_fix.py, onadata/libs/utils/logger_tools.py
Run `python3 manage.py soft_delete_orphan_attachments_2_023_37c_fix` (again) inside the KoboCAT container to fix existing submissions.
See #905.
=> Fix missing encrypted files when exporting or viewing submitted data 

.gitlab-ci.yml
1. [ ] If you've added code that should be tested, add tests
2. [ ] If you've changed APIs, update (or create!) the documentation
3. [X] Ensure the tests pass
4. [X] Make sure that your code lints and that you've followed [our coding style](https://github.com/kobotoolbox/kpi/blob/master/CONTRIBUTING.md)
5. [X] Write a title and, if necessary, a description of your work suitable for publishing in our [release notes](https://community.kobotoolbox.org/tag/release-notes)
6. [X] Mention any related issues in this repository (as #ISSUE) and in other repositories (as kobotoolbox/other#ISSUE)
7. [ ] Open an issue in the [docs](https://github.com/kobotoolbox/docs/issues/new) if there are UI/UX changes
Fixes an issue with Docker images that cause GitLab CI to fail on the 'build' step.
Same fix for …
=> Pin docker/dind to 24.0.6 to fix CI

onadata/apps/api/tools.py, onadata/apps/main/context_processors.py, onadata/apps/main/tests/test_custom_context_processors.py, onadata/libs/utils/user_auth.py, onadata/settings/base.py
Remove Django sites framework, which duplicates functionality of existing django settings.
Resolves TASK-424
For reference, the default is:
```
In [6]: site.name
Out[6]: 'example.com'
In [7]: site.domain
Out[7]: 'example.com'
In [10]: settings.KOBOCAT_PUBLIC_HOSTNAME
Out[10]: 'kc.kobotoolbox.org'
```
=> Remove sites framework

.gitlab-ci.yml
This PR adds a job to automatically deploy Kobocat branches that start with `feature/` to k8s. It's pretty much a straight port of the job with the same name (`deploy-staging`) from kpi's `.gitlab-ci.yml`.
You can see a sample run [here](https://gitlab.com/kobo_toolbox/kobocat/-/jobs/6032640880) using `feature/tri` - the failed runs can safely be ignored, I just needed to protect `feature*` branches in GitLab. That code triggered a deployment to https://kf.tri.kbtdev.org/ , which I've verified as successful.
=> add job to deploy kobocat to staging if branch starts with 'feature/'

onadata/apps/logger/migrations/0034_set_require_auth_at_project_level.py
It's not a thing most people should do!
=> Update backward migration message when going from project-level to account-level anonymous submission permissions

onadata/apps/logger/maintenance_tasks.py, onadata/apps/logger/tasks.py, onadata/apps/logger/tests/models/test_instance.py, onadata/settings/base.py
Adds a daily `perform_maintenance` Celery task and implements cleanup for old django-reversion revisions based on work in #579 . 
The actual revision cleanup work is drastically simplified here. The django admin command used in the previous PR was based on django-reversion's own admin command and was made much more complicated than necessary for our use case because of the abstraction the django-reversion command affords. The tables for revisions and versions in Kobocat are potentially enormous, so I decided that the simplest approach was the best, rather than filtering and iterating over hundreds of millions of rows.
=> Add revision cleanup task

onadata/apps/storage_backends/s3boto3.py
Fix old bug re-introduced with Django 4.2 upgrade in `2.024.12`
django-storages has been refactored in version `1.14` which has voided the monkey-patch we were applying with previous versions. 
#475
=> Fix corrupted large ZIP files with AWS S3 storage
