.travis.yml, fabfile.py
Will provide for automatic deployment to staging server
=> Travis configuration; Fabfile improvements

onadata/apps/viewer/templates/survey.kml, onadata/libs/utils/export_tools.py
=> KML output to contain UUIDs instead of all survey data

onadata/apps/api/viewsets/briefcase_api.py, onadata/apps/logger/views.py, onadata/apps/main/views.py, onadata/apps/restservice/views.py, onadata/apps/stats/views.py, onadata/apps/viewer/views.py, onadata/libs/utils/export_tools.py, onadata/libs/utils/logger_tools.py
=> Change all XForm and DataDictionary queries from __iexact to __exact

onadata/libs/utils/export_tools.py
=> Exclude deleted instances from KML exports

onadata/apps/main/locale/en/LC_MESSAGES/django.po, onadata/apps/main/locale/es/LC_MESSAGES/django.po, onadata/apps/main/locale/fr/LC_MESSAGES/django.po, onadata/apps/main/locale/it/LC_MESSAGES/django.po, onadata/apps/main/locale/km/LC_MESSAGES/django.po, onadata/apps/main/locale/ne/LC_MESSAGES/django.po, onadata/apps/main/locale/nl/LC_MESSAGES/django.po, onadata/apps/main/locale/zh/LC_MESSAGES/django.po, onadata/apps/main/models/user_profile.py
New wording per @tinok. Only Spanish translation updated.
=> Clarify description UserProfile.require_auth

onadata/apps/main/views.py, onadata/apps/viewer/views.py
Fixes TP 1694: User with 'can view' permissions can delete submission through map view
=> Fixes TP 1694

onadata/apps/viewer/static/js/instance.js
by making updateButtons() compatible with kobocat-template CSS changes (and hopefully more robust in general).
=> Fix instance delete feature

onadata/apps/logger/views.py, onadata/apps/main/urls.py, requirements/base.pip
Biggest change is moving to a newer revision of `pyxform`.
=> Spss labels

onadata/apps/api/tools.py, onadata/apps/api/viewsets/briefcase_api.py, onadata/apps/api/viewsets/connect_viewset.py, onadata/apps/api/viewsets/xform_viewset.py, onadata/libs/permissions.py, onadata/libs/utils/logger_tools.py
=> Use UserProfile.objects.get_or_create(user=user) instead of user.profile

onadata/apps/api/management/commands/set_api_permissions.py
See https://github.com/onaio/onadata/commit/0e8d08c0c4ac65d930fb721ff9ca8721c82e6888
=> Have manage.py set_api_permissions apply model-level permissions

onadata/apps/logger/views.py
... instead of the generic 404 error page.
**This also fixes getting the 500 error** if you try to create an Excel Analyzer export while an XLS export is being generated (**Pending...**).
Note that we could add `internal_state=Export.SUCCESSFUL` for `Export.objects.filter` line just above the changed lines to just take successful exports into account, but instead we preferred to show more verbose error messages about what's going on.
The template for rendering the error is called `404_xls_analyzer_error.html` and is in the PR https://github.com/kobotoolbox/kobocat-template/pull/71 .
=> Show verbose error messages when Excel Analyzer can't be generated

onadata/settings/kc_environ.py
Thanks to @esmail for `EMAIL_BACKEND` code
=> Read S3-related information from environment

onadata/apps/logger/models/xform.py, onadata/apps/logger/views.py, onadata/apps/main/urls.py, onadata/apps/viewer/models/export.py, onadata/apps/viewer/tasks.py, onadata/libs/utils/analyser_export.py, onadata/libs/utils/export_tools.py, requirements/base.pip
Tested locally in Vagrant. Corresponding template change in kobotoolbox/kobocat-template#73.
=> Analyser export list

onadata/libs/serializers/data_serializer.py
Restores proper exception handling. Fixes #125.
http://www.django-rest-framework.org/topics/3.0-announcement/#changes-to-the-custom-field-api
=> Improve check for invalid object in `to_native()`. Fixes #125.

onadata/libs/serializers/data_serializer.py
Fix for https://github.com/kobotoolbox/kobo-docker/issues/12
=> Fix mistake in dfd9735

onadata/libs/serializers/data_serializer.py
Fixes https://github.com/kobotoolbox/kobo-docker/issues/12
=> Fix "API calls are returned empty" (kobo-docker #12)

onadata/apps/main/views.py
=> Remove `#qr` from EE QR code URL

Dockerfile
=> Closes #201.

onadata/apps/survey_report/templates/survey_report/auto_report.html, onadata/apps/survey_report/templates/survey_report/export_menu.html
Reverts kobotoolbox/kobocat#204
=> Revert "Header fix"

Dockerfile
=> Let's try that again, but unconditionally installing requirements.

onadata/koboform/__init__.py
=> Don't ref. before assignment

onadata/apps/main/templates/form_photos.html, onadata/apps/main/templates/show_form_settings.html, onadata/apps/main/urls.py, onadata/apps/main/views.py
Sets up standalone settings screen. Minor fix: "no photos" message displayed when gallery is empty.
=> Kpi prep for 716

onadata/apps/api/viewsets/xform_list_api.py
* `/user/formList` returns the forms belonging to `user`
* Accessible to anyone unless `user` has ticked `Require authentication to see forms and submit data`
* If `Require authentication to see forms and submit data` IS ticked, the endpoint returns only forms belonging to `user` which are also accessible to the currently-logged-in user
* `/formList` returns all forms accessible to the currently-logged-in user, including those shared by other users
* Requires authentication and rejects any anonymous request
Fixes #200
=> Fix handling of `/formList` auth. and filtering

onadata/apps/main/forms.py
Per https://github.com/kobotoolbox/kpi/issues/821
=> Remove user profile fields from settings form

onadata/apps/viewer/pandas_mongo_bridge.py
=> Handle notes in CSV the same as other exports

onadata/libs/serializers/team_serializer.py
- update method was throwing exception ` AttributeError: 'Team' object has no attribute 'get'` as `attrs` and `instance` where swapped
- `attrs` shouldn't be optional
- fix updating to new team name
- save to database upon updating
=> fix update method body and signature

onadata/apps/logger/views.py
Show the number of objects created each month instead of listing every object.
Fixes #284
=> Change `superuser_stats` to report monthly counts

onadata/apps/main/views.py
This change should have been included in 6eada24
=> Do not expect `email` in the profile form

.dockerignore, .travis.yml, Dockerfile, Dockerfile.kobocat_base, docker/backup_media.bash, docker/backup_media_crontab.envsubst, docker/init.bash, docker/run_tests.bash
Enable automatically backing up the `media` directory in Docker.
Part of kobotoolbox/kobo-docker#10.
=> Docker media backup.

onadata/settings/common.py
Helpful for API documentation; see https://www.flowdock.com/app/kobotoolbox/kobo/threads/TwkLnfhsilGyROIpTHbyDBo3zTQ
=> Read DJANGO_SITE_ID from the environment

onadata/apps/export/views.py, onadata/apps/survey_report/views.py
Fixes #317; removes dead code; strips useless whitespace from `onadata/apps/survey_report/views.py`
=> Fix str-to-bool logic for `hierarchy_in_labels`

fabfile/docker.py
=> Omit service name for `docker-compose up -d`

onadata/apps/logger/views.py
Rename confusing parameter `any_day` to `any_date`
Fixes #319
=> Order by primary key when getting last object

onadata/apps/restservice/services/generic_json.py
=> JSON POST fix

Dockerfile, docker/kobocat.ini
Remove some commented-out configuration.
=> Only log uWSGI output to a file in Docker.

onadata/apps/logger/views.py
=> Reflect `pyxform` refactoring of `survey_from()`.

onadata/apps/viewer/models/parsed_instance.py, onadata/libs/serializers/data_serializer.py
* needs to be tested on a working deployment
=> closes #353

onadata/settings/common.py
=> allowing SVG media attachments.

docker/kobocat.ini
=> Enable uWSGI threads per Raven requirements

requirements/base.pip
=> Upgrade Raven in attempt to resolve uWSGI deadlock

onadata/apps/main/service_health.py, onadata/apps/main/urls.py
=> Basic service health checker for load balancers

onadata/apps/logger/management/commands/fix_root_node_names.py, onadata/apps/logger/management/commands/populate_xml_hashes_for_instances.py, onadata/apps/logger/migrations/0003_instance_xml_hash.py, onadata/apps/logger/migrations/0005_instance_xml_hash.py, onadata/apps/logger/models/instance.py, onadata/libs/utils/logger_tools.py
=> Speed up duplicate submission checks

onadata/settings/common.py
=> Include mandatory setting in `common.py`

onadata/apps/logger/tasks.py
=> Optimize superuser_stats by running fewer queries

onadata/apps/export/__init__.py, onadata/apps/export/urls.py, onadata/apps/export/views.py, onadata/apps/survey_report/views.py
=> Fix "Include groups in headers" checkbox

onadata/settings/common.py
Closes #436. @noliveleger, a one-liner for you :)
=> Disable registrations; mainly precautionary.

onadata/apps/logger/models/xform.py
=> Escape form titles when including in XML

onadata/apps/logger/xform_instance_parser.py, onadata/apps/viewer/management/commands/remongo.py, onadata/apps/viewer/models/parsed_instance.py, onadata/libs/utils/logger_tools.py, onadata/settings/kc_environ.py
=> Make `sync_mongo` and `remongo` commands stop on errors - fix

onadata/apps/api/viewsets/xform_list_api.py, onadata/libs/utils/viewer_tools.py
=> Changed query to retrieve XForm user can view - fix

docker/kobocat.ini
Mirrors kobotoolbox/kpi@d30c748
=> Configure uWSGI process count from the environment

fabfile/docker.py
=> Update base image on every Fabric build

onadata/apps/logger/models/instance.py
* reducing the number of queries;
* avoiding reading and writing large and irrelevant `XForm` attributes, like
`xml` and `json`.
Previously, calling `update_xform_submission_count()` created queries like this:
```
postgres_1        | 2018-09-19 21:27:36 GMT LOG:  statement: BEGIN
postgres_1        | 2018-09-19 21:27:36 GMT LOG:  statement: SELECT "logger_xform"."id", "logger_xform"."xls", "logger_xform"."json", "logger_xform"."description", "logger_xform"."xml", "logger_xform"."user_id", "logger_xform"."require_auth", "logger_xform"."shared", "logger_xform"."shared_data", "logger_xform"."downloadable", "logger_xform"."allows_sms", "logger_xform"."encrypted", "logger_xform"."sms_id_string", "logger_xform"."id_string", "logger_xform"."title", "logger_xform"."date_created", …
```
=> Improve submission count efficiency by

onadata/apps/logger/management/commands/delete_revisions.py
Same as `kpi` PR. I've added the 2 `vacuum` options.
=> Extends 'deleterevisions' management command to handle chunks

onadata/apps/api/viewsets/xform_viewset.py
=> Allow CSV format from form detail API endpoint.

requirements/base.pip
=> Bumped redis pip lib to 3.2.0

onadata/libs/utils/image_tools.py
=> Fixed thumbnails creation. 

onadata/apps/api/tools.py, onadata/apps/api/viewsets/data_viewset.py, onadata/apps/viewer/models/parsed_instance.py
Should be merged before https://github.com/kobotoolbox/kpi/pull/2196
=> Allow delete of validation status (single or multiple at once)

.gitmodules, Dockerfile, Dockerfile.kobocat_base, onadata/settings/kc_environ.py, onadata/settings/test_environ.py
Reverts kobotoolbox/kobocat#520
=> Revert "Add `kobocat-template` as a Git submodule"

onadata/apps/logger/tasks.py
=> Limit superuser_stats to current and previous month

onadata/apps/restservice/management/commands/update_kpi_hooks_endpoint.py, onadata/apps/restservice/signals.py
Related to https://github.com/kobotoolbox/kpi/pull/2186
Postgres will need to be updated with this command:
`UPDATE restservice_restservice SET service_url = REGEXP_REPLACE(service_url, '/assets/([^/]*)/submissions/', '/assets/\1/hook-signal/')
where service_url like '/assets/%';`
or 
A management command exists in the PR #531 (Released with Kpi database Part III).
`./manage.py update_kpi_hooks_endpoint`
=> Changed 'kpi' endpoint for hook signal

onadata/apps/api/permissions.py
=> Non-owner users with 'validation_xform' permissions cannot validate submissions.

onadata/apps/api/exceptions.py, onadata/apps/api/urls.py, onadata/apps/api/viewsets/data_viewset.py, onadata/apps/logger/management/commands/clean_duplicated_submissions.py, onadata/apps/logger/management/commands/update_is_sync_with_mongo.py, onadata/apps/viewer/models/parsed_instance.py
Allows bulk delete of submissions.
Related to https://github.com/kobotoolbox/kpi/pull/2321. It has to be merged before `kpi`'s PR.
=> Bulk delete feature

onadata/apps/logger/exceptions.py
=> Missing import fix

onadata/apps/restservice/views.py
Additionally, do not allow them to be deleted via legacy view code
=> Do not show KPI hooks in Legacy Rest Services list

onadata/libs/utils/redis_helper.py, onadata/settings/common.py, onadata/settings/kc_environ.py
To be merged with
kobo-install: kobotoolbox/kobo-install#72
KPI: https://github.com/kobotoolbox/kpi/pull/2574
kobo-docker: https://github.com/kobotoolbox/kobo-docker/pull/266
=> Support special characters in MongoDB and Redis password

kobocat-template/templates/base.html, onadata/apps/main/static/js/application.js, onadata/settings/test_environ.py
=> Set the `secure` and `httpOnly` flags on cookies

onadata/apps/main/views.py, requirements/base.pip
Closes KC part of https://github.com/kobotoolbox/tasks/issues/341
Related to https://github.com/kobotoolbox/kpi/pull/2596
Use new package: https://github.com/kobotoolbox/ssrf-protect
=> Protect form media endpoints against SSRF attacks

requirements/base.pip
=> Updated SSRF Protect version

onadata/apps/api/permissions.py, onadata/apps/api/tests/viewsets/test_note_viewset.py, onadata/apps/api/urls.py, onadata/apps/api/viewsets/note_viewset.py
There is one exception in this PR (as requested in issue description)
To add notes, users need "edit" access to submissions
Closes #601
=> Access to notes follow submission permissions

onadata/apps/api/viewsets/metadata_viewset.py, onadata/apps/logger/models/attachment.py, onadata/apps/logger/models/xform.py, onadata/apps/main/models/meta_data.py, onadata/libs/filters.py
closes #267 (and should closes #584).
Also needed for https://github.com/kobotoolbox/kpi/pull/2537 and should be merged prior to KPI PR
=> Improved MetaData files upload and delete.

onadata/settings/common.py
=> Increased request body & file upload max size

onadata/apps/viewer/views.py
=> Strip out query-string garbage added by Galleria

onadata/apps/main/views.py
=> Encode image filenames when building gallery URLs

onadata/apps/api/viewsets/xform_list_api.py
Should increase performance for accounts that have large numbers of forms. Closes #230
=> Support the OpenRosa `formID` param in `formList`

onadata/apps/api/tests/viewsets/test_xform_list_api.py
Credit to onaio/onadata@da6f69a
=> Add test for `formList/?formID=[id_string]`

onadata/apps/logger/migrations/0014_attachment_add_media_file_size.py, onadata/apps/logger/models/attachment.py
Unilateral self-merge; sorry if this causes us to rename other migration files in pending PRs :sob:
Toward #517
=> Store attachment file size in the database

kobocat-template/templates/show.html
=> Temporarily restore disabled HTML divs in project detail view

locale/en/LC_MESSAGES/django.po, onadata/libs/templates/registration/logout.html
=> Remove old logout message

.github/workflows/pytest.yml
Fixed the apt dependencies falling out of sync with the Ubuntu 20.04 server causing pytest.yml runs to fail
=> Fixed apt dependencies breaking

onadata/apps/api/viewsets/data_viewset.py
=> Fix docs typo

onadata/apps/viewer/management/commands/sync_mongo.py
=> Fix argparse config for sync_mongo

onadata/apps/survey_report/views.py, onadata/apps/viewer/models/parsed_instance.py, onadata/libs/utils/export_tools.py, onadata/libs/utils/logger_tools.py, onadata/settings/common.py
Added a timeout to mongo queries to prevent hour long requests to the database
fixes kobotoolbox/kpi#3158
related kobotoolbox/kpi#3206
=> Added max_time_ms to mongo queries

onadata/apps/api/urls.py, onadata/apps/main/views.py, onadata/libs/serializers/note_serializer.py
Cleaned up items according to the KoBoCat 2.0 punch list
Related #691 
Part of #682
=> Python3 and Django2.2 upgrade punch list items

onadata/apps/main/tests/test_form_api.py, onadata/apps/main/urls.py, onadata/apps/main/views.py
Re-added an endpoint for Kobocat 2.0
`<username>/forms/<id_string>/api` has been re-added along with the unit tests
=> Added missing api endpoint

kobocat-template/templates/profile.html, onadata/apps/main/views.py
closes #705 
blocked by kobotoolbox/kpi#3174
=> Kobocat support for xform sync

kobocat-template/templates/profile.html, onadata/apps/main/views.py
See #706 for the work of substance
=> Apply cosmetic improvements to self-service sync

kobocat-template/templates/show.html, onadata/apps/main/urls.py, onadata/apps/main/views.py
Readded the ability to download and delete background documents
Permissions on the servers will need to be set with `chown -R "kobo" "/srv/src/kobocat"` to be able to delete background documents
=> Readd background documents

Dockerfile, README.md, onadata/apps/main/views.py
Only allow users with permission to submit to a form to download that form's associated media files
=> Fix form media permissions

onadata/settings/base.py
=> Update supported media types

onadata/libs/utils/viewer_tools.py
=> Disable seeking when writing ZIP exports

onadata/apps/api/viewsets/data_viewset.py
Disabled the redundant pre-delete signal for bulk_delete.
Fixes #735
=> Disabled pre-delete signal for bulk_delete

onadata/apps/api/permissions.py, onadata/apps/api/tests/viewsets/test_data_viewset.py, onadata/apps/api/viewsets/data_viewset.py, onadata/libs/utils/viewer_tools.py
=> Refactor Enketo endpoints for edit and view

onadata/apps/api/models/one_time_auth_token.py, onadata/libs/utils/logger_tools.py
This fixes bulk editing without having KPI add synthetic referrers.
A new approach will likely be used when tackling kobotoolbox/kpi#3383.
=> Check for one-time-authentication header before verifying referrer URL 

onadata/apps/api/viewsets/xform_viewset.py
Partially reverts f46eb3177.
@JacquelineMorrissette, would you mind glancing at this? I've already deployed it to UNHCR's server to solve an urgent problem for them, but it's always nice to get extra eyes on a change before it's finalized.
=> Restore /api/v1/forms/<formid>/enketo endpoint

dependencies/pip/dev.txt, dependencies/pip/prod.txt, dependencies/pip/requirements.in, dependencies/pip/requirements.txt, onadata/apps/api/tests/viewsets/test_xform_viewset.py
Upgrade pyxform with bug fixes and new `allow-mock-accuracy` parameter for geo questions ([change log](https://github.com/XLSForm/pyxform/blob/master/CHANGES.txt#L5-L29)).
closes #777
=> Upgrade pyxform to `v1.7.0`

kobocat-template/templates/base.html
=> Fix 2 static file paths - #764

onadata/settings/dev.py, onadata/settings/prod.py
Related to https://github.com/kobotoolbox/kpi/pull/3717
=> Fix django-redis-sessions url

dependencies/pip/dev.txt, dependencies/pip/prod.txt, dependencies/pip/requirements.in, dependencies/pip/requirements.txt, onadata/apps/storage_backends/s3boto3.py, onadata/settings/base.py
- Upgrade django-storages
- Replace fork with subclass for tellable storage
- Add support for Azure Blob storage
Related to https://github.com/kobotoolbox/kpi/pull/3794
=> Django storages upgrade + azure

onadata/settings/base.py
Changed the default database to read from `KC_DATABASE_URL` and fallback to `DATABASE_URL`
closes #804
=> Changed how the default database URL is read

onadata/settings/base.py
Add support to mongo replica set by setting MONGO_DB_URL environment variable.
Related to https://github.com/kobotoolbox/kpi/pull/3838
=> Add support for MONGO_DB_URL replica set strings

dependencies/pip/dev.txt, dependencies/pip/prod.txt, dependencies/pip/requirements.txt, pip-compile.sh
Related to https://github.com/kobotoolbox/kpi/pull/3868
=>  Add pip compile script to work around pip tools python version limitation

onadata/apps/viewer/models/parsed_instance.py
Fix #837 by raising exception instead of only logging errors when saving submission to MongoDB
=> Reject submissions with error if they cannot be written to MongoDB

.gitlab-ci.yml
Add SAST to Gitlab pipeline for automated security testing
=> Add SAST to Gitlab pipeline

onadata/settings/base.py
Change schedule of daily submission count deletion from every 0 seconds to once everyday at midnight UTC.
=> Fix wrong schedule for submission counter background task

onadata/apps/logger/models/monthly_xform_submission_counter.py, onadata/apps/logger/tests/models/test_xform_submission_counters.py
Fixes `IntegrityError` when deleting two projects in the same month
=> Merge deleted xforms' monthly submission counters

onadata/apps/logger/management/commands/populate_submission_counters.py, onadata/apps/logger/models/monthly_xform_submission_counter.py, onadata/apps/logger/models/xform.py
The management command `populate_submission_counters` updates all users' projects instead of only the one.
=> Fix omitted submission counters calculation when running management command

onadata/settings/base.py
Make the user session cookie configurable via kobo-install
kobotoolbox/kobo-install#215
kobotoolbox/kpi#4238
=> Customize user session cookie age

dependencies/pip/dev_requirements.txt, dependencies/pip/requirements.txt
Stay in step with kobotoolbox/kpi#4365
=> Upgrade django-storages to 1.13.2

.gitlab-ci.yml
See https://github.com/kobotoolbox/kpi/commit/f735a918a3691fe9335425b7ca50f4f8431725cc
=> Replace slashes with dashes in Docker image tags

onadata/apps/viewer/views.py
=> Stop returning 500 for failed authentication to the media endpoint

.gitlab-ci.yml
=> Update Helm version, namespace, deployment name for "beta" staging environment

onadata/apps/logger/migrations/0034_set_require_auth_at_project_level.py
Fix a wrong filter when fetching projects to change
=> Fix wrong OpenRosa server urls when migrating require auth from account level to project level

dependencies/pip/dev_requirements.txt, dependencies/pip/requirements.in, dependencies/pip/requirements.txt, onadata/settings/base.py
=> Fix 500 error when submitting data after changing the password
